// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzH26-VT-mDJZL5-Xh9DoWlSL56ED9Q44',
    appId: '1:1036306872826:web:0d43d2f00011c9f008cc43',
    messagingSenderId: '1036306872826',
    projectId: 'ligueypro',
    authDomain: 'ligueypro.firebaseapp.com',
    storageBucket: 'ligueypro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVp2hgX3hKMinqjH5B38hA-YrluioT-7E',
    appId: '1:1036306872826:android:f3ed7a9a92bb880908cc43',
    messagingSenderId: '1036306872826',
    projectId: 'ligueypro',
    storageBucket: 'ligueypro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB2JMrNEZJbM8V0VwH-3QtNcB7HUg0_Zo',
    appId: '1:1036306872826:ios:ca7f25a85163677b08cc43',
    messagingSenderId: '1036306872826',
    projectId: 'ligueypro',
    storageBucket: 'ligueypro.firebasestorage.app',
    iosBundleId: 'sn.digitprestconsulting.ligueypro',
  );

}